version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: weather_api
    restart: "no"
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgresql
    volumes:
      - .:/rails:cached
      - bundle-volume:/usr/local/bundle

  postgresql:
    image: postgres
    restart: "no"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgresdb:/var/lib/postgresql/data/

volumes:
  postgresdb:
  bundle-volume: